safe: true
lsi: false
highlighter: pygments
markdown: redcarpet

redcarpet:
  extensions: ['footnotes']

exclude: ['vendor']

paginate: 6
paginate_path: /page:num/

defaults:
 -
  scope:
   type: posts
  values:
   layout: post
